import type { Metadata } from "next";
import { Inclusive_Sans, Sofia_Sans } from "next/font/google";
import "./globals.css";
import ProfileCard from "@/components/ProfileCard";
import Sidebar from "@/components/Sidebar";

const font = Sofia_Sans({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} flex items-center justify-between gap-x-10 p-6 min-h-screen`}
      >
        <ProfileCard />
        {children}
        <Sidebar />
      </body>
    </html>
  );
}
